AWSTemplateFormatVersion: '2010-09-09'
Description: Criação do cluster EKS com Role e configurações de rede

Parameters:
  ClusterName:
    Type: String
    Description: Nome do cluster EKS

  KubernetesVersion:
    Type: String
    AllowedValues: ['1.31', '1.32', '1.33']  # ATUALIZE AQUI conforme necessário
    Description: Versão do Kubernetes permitida para o cluster EKS

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID da VPC onde o cluster será criado

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lista de Subnet IDs (privadas)

  PrimarySecurityGroupId:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: SG principal

  TagENV:
    Type: String
    AllowedValues: ['dev']

  TagCC:
    Type: String
    AllowedValues:   👈 Adicionar a tags para centro de custo.
      - '1111 - Centro de custo'


  TagVertical:
    Type: String
    AllowedValues: ['ti']   # 👈 Adicionar tags de indentificação da area

  TagServico:
    Type: String
    AllowedValues: ['eks']

  TagTexto:
    Type: String
    AllowedValues: ['eks']

Conditions:   
  UseAL2023: !Or
    - !Equals [!Ref KubernetesVersion, "1.33"]
    - !Equals [!Ref KubernetesVersion, "1.34"]
    - !Equals [!Ref KubernetesVersion, "1.35"]  # pode adicionar novas versões futuramente

Resources:
  IAMPoliciesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://***.s3.us-east-1.amazonaws.com/path"  # 👈 Adicionar a URLtemplate aonde ta armazenado os templates EKS no s3
      Parameters:
        ClusterName: !Ref ClusterName  # ou defina como quiser

  EKSClusterRole:
    Type: AWS::IAM::Role
    DependsOn: IAMPoliciesStack
    Properties:
      RoleName: !Sub "EKSClusterRole-${ClusterName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [eks.amazonaws.com]
            Action: [sts:AssumeRole]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - !GetAtt IAMPoliciesStack.Outputs.Policy1Arn
        - !GetAtt IAMPoliciesStack.Outputs.Policy2Arn
      Tags:
        - Key: Name
          Value: !Sub "EKSClusterRole-${ClusterName}"

  # Security Groups
  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG principal do cluster
      VpcId: !Ref VpcId

  AdditionalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG adicional do cluster
      VpcId: !Ref VpcId

  # Role do NodeGroup
  NodeGroupRole:
    Type: AWS::IAM::Role
    DependsOn: EKSCluster
    Properties:
      RoleName: !Sub "EKSNodeGroupRole-${ClusterName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: [sts:AssumeRole]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - !GetAtt IAMPoliciesStack.Outputs.Policy3Arn
        - !GetAtt IAMPoliciesStack.Outputs.Policy4Arn
        - !GetAtt IAMPoliciesStack.Outputs.Policy5Arn
        - !GetAtt IAMPoliciesStack.Outputs.Policy6Arn

  # Cluster EKS
  EKSCluster:
    Type: AWS::EKS::Cluster
    DependsOn: EKSClusterRole
    DeletionPolicy: Retain
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
          - !Ref AdditionalSecurityGroup
        SubnetIds: !Ref SubnetIds
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
        PublicAccessCidrs:  # 👈 Adicionar todos os Ips publicos para request externos
        - 172.169.172.169/32

      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: Name
          Value: !Ref ClusterName
        - Key: ENV
          Value: !Ref TagENV
        - Key: CC
          Value: !Select [0, !Split [' - ', !Ref TagCC]]
        - Key: Vertical
          Value: !Ref TagVertical
        - Key: Servico
          Value: !Ref TagServico
        - Key: Contexto
          Value: !Ref TagTexto

  # Security Group dos Nodes
  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para os nodes do EKS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      # Permitir que o cluster EKS fale com os nodes
        - IpProtocol: tcp
          FromPort: 10250
          ToPort: 10250
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
      # DNS interno (CoreDNS)
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          SourceSecurityGroupId: !Ref ClusterSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0


  # Stack externo do LaunchTemplate
  EKSLaunchTemplateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://***.s3.us-east-1.amazonaws.com/path"  # 👈 Adicionar a URLtemplate aonde ta armazenado os templates EKS no s3
      Parameters:
        ClusterName: !Ref ClusterName
        KubernetesVersion: !Ref KubernetesVersion
        UseAL2023: !If [UseAL2023, "true", "false"]
        FallbackAMI: ami-0b3a73487ec93ea0b 👈 adicionar a ami desejada para o Fallback
        NodeSecurityGroup: !Ref NodeSecurityGroup   # 👈 AGORA está garantido que o recurso já existe

  # NodeGroup usando LaunchTemplate
  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster   # apenas o cluster precisa existir antes
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Sub "${ClusterName}-NodeGroup"
      NodeRole: !GetAtt NodeGroupRole.Arn
      Subnets: !Ref SubnetIds
      ScalingConfig:
        MinSize: 1
        MaxSize: 2
        DesiredSize: 1
      LaunchTemplate:
        Id: !GetAtt EKSLaunchTemplateStack.Outputs.LaunchTemplateId
        Version: !GetAtt EKSLaunchTemplateStack.Outputs.LaunchTemplateVersion
      Labels:
        role: worker
      Tags:
        Name: !Sub "${ClusterName}-ng"
        ENV: !Ref TagENV
        CC: !Select [0, !Split [' - ', !Ref TagCC]]
        Vertical: !Ref TagVertical
        Servico: !Ref TagServico
        Contexto: !Ref TagTexto

  # Stack de Addons
  EKSAddonsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EKSCluster
    Properties:
      TemplateURL: "https://***.s3.us-east-1.amazonaws.com/path"  # 👈 Adicionar a URLtemplate aonde ta armazenado os templates EKS no s3
      Parameters:
        ClusterName: !Ref ClusterName
        KubernetesVersion: !Ref KubernetesVersion

Outputs:
  ClusterName:
    Description: Nome do Cluster EKS
    Value: !Ref ClusterName

  ClusterARN:
    Description: ARN do Cluster criado
    Value: !GetAtt EKSCluster.Arn

  ClusterRoleARN:
    Description: ARN da Role associada ao Cluster
    Value: !GetAtt EKSClusterRole.Arn

  NodeGroupName:
    Description: Nome do NodeGroup criado
    Value: !Ref EKSNodeGroup
